name: Trigger Portainer Webhook

on:
  push:
    branches:
      - develop  # Trigger on commits to the main branch

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Portainer Webhook
      run: |
          curl -L -X POST \
            -H "CF-Access-Client-Id: ${{ secrets.CF_CLIENT_ID }}" \
            -H "CF-Access-Client-Secret: ${{ secrets.CF_CLIENT_SECRET }}" \
            ${{ secrets.PORTAINER_WEBHOOK_URL }}

